"""AmberMD Agent MCP Server — FastMCP wrapper over md_agent.py."""
import sys
from pathlib import Path
from typing import Annotated, Optional

from fastmcp import FastMCP
from pydantic import Field

sys.path.insert(0, str(Path(__file__).parent))
import md_agent

mcp = FastMCP("amber-md-agent")

# ─── Connectivity ─────────────────────────────────────────────────────────────

@mcp.tool()
def ping() -> dict:
    """Health check. Returns ok if server is running."""
    return {"status": "ok", "message": "amber-md-agent MCP server running"}


# ─── PDB Tools ────────────────────────────────────────────────────────────────

@mcp.tool()
def fetch_pdb(
    pdb_id: Annotated[str, Field(description="4-character PDB ID e.g. '1IEP'")],
    output_dir: Annotated[str, Field(description="Directory to save .pdb file")] = ".",
) -> dict:
    """Fetch structure from RCSB PDB. Returns local file path."""
    try:
        if not pdb_id:
            raise ValueError("pdb_id cannot be empty")
        result = md_agent.fetch_pdb(pdb_id, output_dir)
        return {"status": "ok", "pdb_file": str(result), "pdb_id": pdb_id}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "fetch_pdb"}


@mcp.tool()
def inspect_pdb(
    pdb_file: Annotated[str, Field(description="Path to .pdb file to inspect")],
) -> dict:
    """Inspect PDB file — chains, residues, ligands, missing atoms, warnings."""
    try:
        result = md_agent.inspect_pdb(pdb_file)
        return {"status": "ok", "inspection": result}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "inspect_pdb"}


@mcp.tool()
def clean_pdb(
    pdb_file: Annotated[str, Field(description="Path to input .pdb file")],
    output_file: Annotated[Optional[str], Field(description="Output path. Defaults to clean.pdb in the same directory as input.")] = None,
    keep_waters: Annotated[bool, Field(description="Retain crystallographic waters")] = False,
    keep_hydrogens: Annotated[bool, Field(description="Retain existing hydrogens")] = False,
) -> dict:
    """Clean PDB — remove HETATM, waters, alt conformations. Returns cleaned file path."""
    try:
        result = md_agent.clean_pdb(pdb_file, output_file, keep_waters, keep_hydrogens)
        return {"status": "ok", "clean_pdb": str(result)}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "clean_pdb"}


@mcp.tool()
def preflight(
    pdb_file: Annotated[str, Field(description="Path to .pdb file for preflight check")],
    check_ligands: Annotated[bool, Field(description="Also check for unparametrized ligands")] = True,
) -> dict:
    """MANDATORY before system build. Checks for gaps, missing atoms, ligands, charge issues."""
    try:
        result = md_agent.preflight(pdb_file, check_ligands)
        return {"status": "ok", "preflight": result}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "preflight"}


# ─── File Writer Tools ────────────────────────────────────────────────────────────

@mcp.tool()
def write_mdin(
    output_path: Annotated[str, Field(description="Path to write .mdin file")],
    namelist_params: Annotated[str, Field(description="JSON string of &cntrl parameters e.g. '{\"imin\":1,\"maxcyc\":1000,\"cut\":8.0}'")],
    title: Annotated[str, Field(description="Title line for mdin file")] = "Generated by AmberMD Agent",
    extra_sections: Annotated[Optional[str], Field(description="Extra sections to append after &cntrl (e.g. &wt, restraints)")] = None,
) -> dict:
    """Write Amber mdin input file from JSON params. Returns file path."""
    try:
        import json
        params = json.loads(namelist_params)
        extra = [extra_sections] if extra_sections else None
        md_agent.write_mdin(output_path, params, title=title, extra_sections=extra)
        return {"status": "ok", "mdin_file": output_path}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "write_mdin"}


@mcp.tool()
def write_tleap(
    output_path: Annotated[str, Field(description="Path to write tLEaP input file")],
    commands: Annotated[str, Field(description="tLEaP commands as newline-separated string")],
) -> dict:
    """Write tLEaP input script. Returns file path."""
    try:
        md_agent.write_tleap(output_path, commands)
        return {"status": "ok", "tleap_file": output_path}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "write_tleap"}


@mcp.tool()
def write_cpptraj(
    output_path: Annotated[str, Field(description="Path to write cpptraj input file")],
    commands: Annotated[str, Field(description="cpptraj commands as newline-separated string")],
) -> dict:
    """Write cpptraj analysis script. Returns file path."""
    try:
        md_agent.write_cpptraj(output_path, commands)
        return {"status": "ok", "cpptraj_file": output_path}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "write_cpptraj"}


@mcp.tool()
def write_groupfile(
    output_path: Annotated[str, Field(description="Path to write REMD/TI groupfile")],
    entries: Annotated[str, Field(description="JSON array of entry dicts e.g. '[{\"mdin\":\"md.in\",\"mdout\":\"md.out\",\"prmtop\":\"sys.prmtop\",\"inpcrd\":\"in.rst7\"}]'")],
) -> dict:
    """Write REMD or TI groupfile. Returns file path."""
    try:
        import json
        parsed = json.loads(entries)
        md_agent.write_groupfile(output_path, parsed)
        return {"status": "ok", "groupfile": output_path}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "write_groupfile"}


@mcp.tool()
def write_file(
    output_path: Annotated[str, Field(description="Path to write file")],
    content: Annotated[str, Field(description="File content as string")],
) -> dict:
    """Write arbitrary text file. Use for custom scripts or config files."""
    try:
        md_agent.write_file(output_path, content)
        return {"status": "ok", "file": output_path}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "write_file"}


@mcp.tool()
def write_slurm(
    output_path: Annotated[str, Field(description="Path to write SLURM job script")],
    commands: Annotated[str, Field(description="Shell commands to run inside job (newline-separated)")],
    job_name: Annotated[str, Field(description="SLURM job name")] = "amber_md",
    work_dir: Annotated[Optional[str], Field(description="Working directory on cluster")] = None,
    gpus: Annotated[Optional[int], Field(description="Number of GPUs (0 = CPU-only, None = use template default)")] = None,
    walltime: Annotated[Optional[str], Field(description="Walltime override HH:MM:SS e.g. '24:00:00'")] = None,
) -> dict:
    """Write SLURM job script. Cluster defaults from scripts/slurm_template.sh."""
    try:
        md_agent.write_slurm_script(
            output_path, commands, job_name=job_name,
            work_dir=work_dir, gpus=gpus, walltime=walltime,
        )
        return {"status": "ok", "slurm_script": output_path}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "write_slurm"}


@mcp.tool()
def write_slurm_array(
    output_path: Annotated[str, Field(description="Path to write SLURM array script")],
    command_template: Annotated[str, Field(description="Command with {SLURM_ARRAY_TASK_ID} placeholder e.g. 'cd window_{SLURM_ARRAY_TASK_ID} && pmemd.cuda -O ...'")],
    array_range: Annotated[str, Field(description="SLURM array spec e.g. '0-23' or '0-11%4' (max 4 concurrent)")],
    job_name: Annotated[str, Field(description="SLURM array job name")] = "amber_array",
    work_dir: Annotated[Optional[str], Field(description="Working directory on cluster")] = None,
    gpus: Annotated[Optional[int], Field(description="GPUs per array task")] = None,
    walltime: Annotated[Optional[str], Field(description="Walltime per task HH:MM:SS")] = None,
) -> dict:
    """Write SLURM array job script. Ideal for umbrella windows, TI lambdas, REMD replicas."""
    try:
        md_agent.write_slurm_array(
            output_path, command_template, array_range,
            job_name=job_name, work_dir=work_dir, gpus=gpus, walltime=walltime,
        )
        return {"status": "ok", "slurm_array_script": output_path}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "write_slurm_array"}


@mcp.tool()
def write_equil_density_script(
    output_path: Annotated[str, Field(description="Path to write SLURM density-convergence script")],
    prmtop: Annotated[str, Field(description="Path to system .prmtop file")],
    rst_in: Annotated[str, Field(description="Input .rst7 restart file")],
    rst_out: Annotated[str, Field(description="Output .rst7 restart file after convergence")],
    mdin_path: Annotated[str, Field(description="Path to equilibration .mdin file or its parent directory")],
    work_dir: Annotated[str, Field(description="Working directory on cluster")],
    job_name: Annotated[str, Field(description="SLURM job name")] = "equil_density",
    prod_mdin: Annotated[Optional[str], Field(description="Production .mdin — submitted automatically after convergence")] = None,
    prod_mdout: Annotated[Optional[str], Field(description="Production .mdout output path")] = None,
    prod_rst: Annotated[Optional[str], Field(description="Production .rst7 output path")] = None,
    prod_nc: Annotated[Optional[str], Field(description="Production trajectory .nc path")] = None,
    temperature: Annotated[float, Field(description="Target temperature in Kelvin")] = 300.0,
) -> dict:
    """Write SLURM script with pmemd.cuda restart loop until density converges to 1.00 g/cc."""
    try:
        md_agent.generate_equil_density_script(
            output_path, prmtop, rst_in, rst_out, mdin_path, work_dir,
            job_name=job_name, prod_mdin=prod_mdin, prod_mdout=prod_mdout,
            prod_rst=prod_rst, prod_nc=prod_nc, temperature=temperature,
        )
        return {"status": "ok", "equil_density_script": output_path}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "write_equil_density_script"}


# ─── SLURM Tools ─────────────────────────────────────────────────────────────

@mcp.tool()
def submit_slurm(
    script_path: Annotated[str, Field(description="Path to SLURM .sh script to submit")],
    cwd: Annotated[Optional[str], Field(description="Working directory for sbatch (default: script directory)")] = None,
) -> dict:
    """Submit SLURM job via sbatch. Returns job_id on success."""
    try:
        result = md_agent.submit_slurm(script_path, cwd=cwd)
        if isinstance(result, dict) and not result.get("success"):
            return {"status": "error", "error": result.get("stderr", "Unknown error"), "tool": "submit_slurm"}
        job_id = result if isinstance(result, str) else result.get("job_id", str(result))
        return {"status": "ok", "job_id": str(job_id), "script": script_path}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "submit_slurm"}


@mcp.tool()
def check_slurm_job(
    job_id: Annotated[Optional[str], Field(description="Specific job ID to check. Omit to list all user jobs.")] = None,
) -> dict:
    """Check SLURM job status. Returns state, elapsed time, and nodes."""
    try:
        result = md_agent.check_slurm_job(job_id=job_id)
        return {"status": "ok", "jobs": result}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "check_slurm_job"}


@mcp.tool()
def cancel_slurm_job(
    job_id: Annotated[str, Field(description="SLURM job ID to cancel")],
) -> dict:
    """Cancel a running or pending SLURM job via scancel."""
    try:
        result = md_agent.cancel_slurm_job(job_id)
        return {"status": "ok", "cancelled_job": job_id, "output": str(result)}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "cancel_slurm_job"}


@mcp.tool()
def slurm_history(
    days: Annotated[int, Field(description="Number of past days to show job history")] = 7,
) -> dict:
    """Show SLURM job history via sacct. Returns completed/failed jobs."""
    try:
        result = md_agent.slurm_job_history(days=days)
        return {"status": "ok", "history": result}
    except Exception as e:
        return {"status": "error", "error": str(e), "tool": "slurm_history"}


if __name__ == "__main__":
    mcp.run()
